// Code generator - converts connected nodes to executable JavaScript

import type { AppNode, AppEdge, GeneratedCode, CodeNodeData, InputNodeData, FunctionNodeData } from './types';

/**
 * Build an adjacency list from edges for traversal
 */
function buildGraph(nodes: AppNode[], edges: AppEdge[]): Map<string, string[]> {
    const graph = new Map<string, string[]>();

    // Initialize all nodes
    nodes.forEach(node => {
        graph.set(node.id, []);
    });

    // Add edges (source -> target)
    edges.forEach(edge => {
        const sources = graph.get(edge.source) || [];
        sources.push(edge.target);
        graph.set(edge.source, sources);
    });

    return graph;
}

/**
 * Topological sort to determine execution order
 */
function topologicalSort(nodes: AppNode[], edges: AppEdge[]): string[] {
    const graph = buildGraph(nodes, edges);
    const inDegree = new Map<string, number>();
    const order: string[] = [];

    // Calculate in-degrees
    nodes.forEach(node => inDegree.set(node.id, 0));
    edges.forEach(edge => {
        inDegree.set(edge.target, (inDegree.get(edge.target) || 0) + 1);
    });

    // Start with nodes that have no dependencies (in-degree = 0)
    const queue: string[] = [];
    inDegree.forEach((degree, nodeId) => {
        if (degree === 0) queue.push(nodeId);
    });

    while (queue.length > 0) {
        const nodeId = queue.shift()!;
        order.push(nodeId);

        const neighbors = graph.get(nodeId) || [];
        neighbors.forEach(neighbor => {
            const newDegree = (inDegree.get(neighbor) || 1) - 1;
            inDegree.set(neighbor, newDegree);
            if (newDegree === 0) queue.push(neighbor);
        });
    }

    return order;
}

/**
 * Get incoming edges for a node
 */
function getIncomingEdges(nodeId: string, edges: AppEdge[]): AppEdge[] {
    return edges.filter(edge => edge.target === nodeId);
}

/**
 * Generate variable name from node ID
 */
function nodeIdToVar(nodeId: string): string {
    return `node_${nodeId.replace(/-/g, '_')}`;
}

/**
 * Generate code from connected nodes
 */
export function generateCode(nodes: AppNode[], edges: AppEdge[]): GeneratedCode {
    const errors: string[] = [];
    const warnings: string[] = [];
    const codeLines: string[] = [];

    // Get execution order
    const executionOrder = topologicalSort(nodes, edges);

    // Check for cycles (if order length doesn't match nodes length)
    if (executionOrder.length !== nodes.length) {
        errors.push('Cycle detected in node connections. Please remove circular dependencies.');
        return { code: '', errors, warnings, executionOrder: [] };
    }

    // Create node lookup
    const nodeMap = new Map<string, AppNode>();
    nodes.forEach(node => nodeMap.set(node.id, node));

    // Header
    codeLines.push('// Generated by Visual Coding Puzzle');
    codeLines.push('// ' + new Date().toISOString());
    codeLines.push('');

    // Generate code for each node in order
    executionOrder.forEach(nodeId => {
        const node = nodeMap.get(nodeId);
        if (!node) return;

        const varName = nodeIdToVar(nodeId);
        const incomingEdges = getIncomingEdges(nodeId, edges);

        switch (node.type) {
            case 'input': {
                const data = node.data as InputNodeData;
                let value = data.value;

                // Format value based on type
                if (data.valueType === 'string') {
                    value = JSON.stringify(value);
                } else if (data.valueType === 'array' || data.valueType === 'object') {
                    try {
                        value = JSON.stringify(JSON.parse(value), null, 2);
                    } catch {
                        warnings.push(`Invalid ${data.valueType} in node "${data.label}"`);
                    }
                }

                codeLines.push(`// Input: ${data.label}`);
                codeLines.push(`const ${varName} = ${value};`);
                codeLines.push('');
                break;
            }

            case 'code':
            case 'function': {
                const data = node.data as CodeNodeData | FunctionNodeData;
                const inputVars = incomingEdges.map(e => nodeIdToVar(e.source));

                codeLines.push(`// ${data.label}`);

                // If has inputs, pass them to the code
                if (inputVars.length > 0) {
                    codeLines.push(`const ${varName}_input = [${inputVars.join(', ')}];`);
                }

                // Wrap code in a function if it's multiline or has inputs
                const code = data.code.trim();
                if (code.includes('\n') || inputVars.length > 0) {
                    codeLines.push(`const ${varName} = (() => {`);
                    if (inputVars.length > 0) {
                        codeLines.push(`  const input = ${varName}_input;`);
                    }
                    code.split('\n').forEach(line => {
                        codeLines.push(`  ${line}`);
                    });
                    codeLines.push(`})();`);
                } else {
                    codeLines.push(`const ${varName} = ${code};`);
                }
                codeLines.push('');
                break;
            }

            case 'output': {
                const inputVar = incomingEdges.length > 0 ? nodeIdToVar(incomingEdges[0].source) : 'undefined';
                codeLines.push(`// Output`);
                codeLines.push(`const ${varName} = ${inputVar};`);
                codeLines.push(`console.log('Result:', ${varName});`);
                codeLines.push('');
                break;
            }
        }
    });

    // Export the final output
    const outputNodes = nodes.filter(n => n.type === 'output');
    if (outputNodes.length > 0) {
        const outputVar = nodeIdToVar(outputNodes[0].id);
        codeLines.push(`// Export result`);
        codeLines.push(`if (typeof module !== 'undefined') {`);
        codeLines.push(`  module.exports = ${outputVar};`);
        codeLines.push(`}`);
    }

    return {
        code: codeLines.join('\n'),
        errors,
        warnings,
        executionOrder
    };
}

/**
 * Execute generated code in a safe sandbox
 */
export function executeCode(code: string): { output: string; error?: string; logs: string[] } {
    const logs: string[] = [];
    let output = '';
    let error: string | undefined;

    try {
        // Create a sandboxed console
        const mockConsole = {
            log: (...args: unknown[]) => {
                logs.push(args.map(a => String(a)).join(' '));
            },
            error: (...args: unknown[]) => {
                logs.push('[ERROR] ' + args.map(a => String(a)).join(' '));
            },
            warn: (...args: unknown[]) => {
                logs.push('[WARN] ' + args.map(a => String(a)).join(' '));
            }
        };

        // Execute with sandboxed console
        const fn = new Function('console', code);
        fn(mockConsole);

        output = logs.join('\n');
    } catch (e) {
        error = e instanceof Error ? e.message : String(e);
    }

    return { output, error, logs };
}

/**
 * Download code as a file
 */
export function downloadCode(code: string, filename: string = 'script.js'): void {
    const blob = new Blob([code], { type: 'text/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}
